//This c++ code is generated by PictoBlox

//Included Libraries
#include <Dabble.h>
#include <Servo.h>

//MACROS are defined here
Servo Servo6;

void setup() {
	//put your setup code here, to run once:
	Dabble.begin(9600);
	Servo6.attach(6);
	
	
}

void loop() {
	//put your main code here, to run repeatedly:
	Dabble.processInput();
	
	
	if(Terminal.compareString("close")) {
		Servo6.write(0);
	}
	if(Terminal.compareString("open")) {
		Servo6.write(45);
	}
}

